name: 'Artifact Download'
description: 'Artifact Download using Backblaze as the backend'
author: 'Rojan Gh.'
inputs:
  name:
    required: true
    description: 'Artifact name'
  path:
    required: false
    description: 'Path to extract the artifact content at'
    default: './'
  key:
    required: true
    description: 'Backblaze application key'
  id:
    required: true
    description: 'Backblaze application key id'
  bucket:
    required: false
    description: 'Backblaze bucket name'
    default: 'github-artifacts'
runs:
  using: 'node16'
  main: 'dist/index.js'
