name: 'Artifact Download'
description: 'Artifact Download using Backblaze as the backend'
author: 'Rojan Gh.'
inputs:
  name:
    required: false
    description: 'Artifact name'
    default: 'artifact'
  path:
    required: false
    description: 'Path of artifact download'
    default: './'
  key:
    required: true
    description: 'Backblaze application key'
  id:
    required: true
    description: 'Backblaze application key id'
  bucket:
    required: false
    description: 'Backblaze bucket name'
    default: 'github-artifacts'
  chunk-size:
    required: false
    description: 'Chunk size for download in MB'
    default: '256'
  threads:
    required: false
    description: 'Number of threads to use for download'
    default: '8'
outputs:
  download-path:
    description: 'Path of artifact download'
runs:
  using: 'node16'
  main: 'dist/index.js'
